---
- name: Create a virtual machine on remote host
  hosts: cloud
  become: yes  
  gather_facts: no  
  
  tasks:
    - name: Install required Python packages
      ansible.builtin.apt:
        name: python3-lxml
        state: present
      when: ansible_python_interpreter == '/usr/bin/python3'

    - name: Download Ubuntu cloud image
      ansible.builtin.get_url:
        url: "https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img"
        dest: "/tmp/ubuntu-focal.qcow2"
        mode: "0644"
        checksum: "sha256:https://cloud-images.ubuntu.com/focal/current/SHA256SUMS"

    - name: Copy base image to libvirt images directory
      ansible.builtin.copy:
        src: "/tmp/ubuntu-focal.qcow2"
        dest: "/var/lib/libvirt/images/myvm.qcow2"
        remote_src: yes
        force: no
        mode: "0660"

    - name: Define the VM domain
      community.libvirt.virt:
        command: define
        xml: |
          <domain type='kvm'>
            <name>myvm</name>
            <memory unit='MiB'>2048</memory>
            <vcpu>2</vcpu>
            <os>
              <type arch='x86_64'>hvm</type>
              <boot dev='hd'/>
            </os>
            <devices>
              <disk type='file' device='disk'>
                <source file='/var/lib/libvirt/images/myvm.qcow2'/>
                <target dev='vda' bus='virtio'/>
              </disk>
              <interface type='network'>
                <source network='default'/>
              </interface>
              <graphics type='vnc' port='-1' listen='0.0.0.0'/>
            </devices>
          </domain>

    - name: Start the VM domain
      community.libvirt.virt:
        name: "myvm"
        state: running
