apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  revisionHistoryLimit: 2 
  replicas: 1
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox:stable          
        command:
        - sh
        - -c
        - |
          until nc -z postgres 5432; do
            echo "waiting for postgres…"
            sleep 2
          done
      containers:
      - name: url-shortener
        image: cr.yandex/crpdicuovcl5jupslln1/url-shortener:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: CONFIG_PATH               
          value: "/app/config.prod.yaml"
        # resources:
        #   requests:
        #     cpu:    "100m"
        #     memory: "64Mi"
        #   limits:
        #     cpu:    "500m"
        #     memory: "256Mi"
